### ISSUE TITLE
When using Auto Switch Authentication of Profiles is not working

### ISSUE THREAD

**Issue by Sharkgamer7777** [bytevet/proxyverse#34]
When using an Auto Switch Proxy entry to use different Proxies for some domains, the authentication on these Proxies is not working (HTTP Error 407). However, when I directly use the profile with configured authentication it is working as intended.
I suppose it is due to the Auto Switch type generating a PAC file internally and thus disabling authentication since PAC does not support authentication within the text.
Would it be possible to resolve this issue so that authentication is also working with Auto Switch?

**Comment by SYM01** [comment]
Hi @Sharkgamer7777 , may I know what brand of browser you are using?
The info is necessary for reproduce. Thank you!

**Comment by Sharkgamer7777** [comment]
Hi @SYM01 
I use Brave v1.75.178 with Chromium Engine v133.0.6943.98

**Comment by SYM01** [comment]
The issue had been resolved in v1.2.3. 

Normally, your Chrome extension would be automatically updated within 24 hours.

**Comment by minalminul** [comment]
Hi,
I am using version 1.2.3 on chrome v138.0.7204.158. The problem is still there if I use the domain, but if I use the URL it runs normally.
